In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
 
items = ['pocketKnife', 'beans', 'potatoes', 'onions', 'sleepingBag', 'rope', 'compass']
survival = [15, 3, 14, 2, 30, 25, 10]
weight = [2, 2, 3, 2, 5, 6, 2]
weightLimit = 15
 
data = pd.DataFrame({'item': items, 'survival': survival, 'weight': weight})
data

item  survival  weight
0  pocketKnife        15       2
1        beans         3       2
2     potatoes        14       3
3       onions         2       2
4  sleepingBag        30       5
5         rope        25       6
6      compass        10       2

[0 1 1 0 1 1 1] 0


In [22]:
genePool = [0, 1]

def get_child(length=7):
    genes = np.random.choice(genePool, size=length)
    return(genes)

def fitness(child):
    net_survival = sum(child * data.survival)
    net_weight = sum(child * data.weight)
    if net_weight > weightLimit:
        return(0)
    else:
        return(net_survival)

x = get_child()
print(x, fitness(x))

[0 0 1 1 0 1 0] 41


In [56]:
def mutate(parent, nbits=1):
    n = np.random.randint(7, size=nbits)
    child = parent.copy()
    for index in n:
        child[index] = 1 - child[index]
    return(child)

x = get_child()

print(x, mutate(x, nbits=3))

[0 0 0 1 0 1 0] [0 0 0 1 0 0 0]


In [68]:
def cross_over(p1, p2):
    n = np.random.choice([1, 2, 3, 4], p = [0.25]*4)
    idxs = np.random.randint(7, size=n)
    c1, c2 = p1.copy(), p2.copy()
    c1[idxs] = p2[idxs]
    c2[idxs] = p1[idxs]
    return(c1, c2)

p1, p2 = get_child(), get_child()
print(p1, p2)
print(cross_over(p1, p2))

[0 1 0 1 0 1 0] [1 1 1 0 1 1 0]
(array([0, 1, 0, 0, 0, 1, 0]), array([1, 1, 1, 1, 1, 1, 0]))


In [87]:
def get_elite(population, frac=0.3):
    population = sorted(population, key=lambda x: fitness(x), reverse=True)
    elite_size = int(np.floor(len(population)*frac))
    return(population[:elite_size])

In [89]:
pop_size = 100
population = [get_child() for _ in range(pop_size)]
elite = get_elite(population)

for iteration in range(40):
    new_population = []
    
    elite_idx = range(len(elite))
    
    while len(new_population) < pop_size:
        mutate_ = np.random.choice([0, 1], p=[0.1, 0.9])
        if mutate_:
            nbits = np.random.choice([1, 2, 3], p=[0.5, 0.25, 0.25])
            parent_idx = np.random.choice(elite_idx)
            new_population.append(mutate(elite[parent_idx], nbits=nbits))
            
        else:
            p1, p2 = np.random.choice(elite_idx, 2)
            c1, c2 = cross_over(elite[p1], elite[p2])
            new_population.extend([c1, c2])
    
    population = new_population
    elite = get_elite(population)

In [92]:
list(zip(elite, [fitness(i) for i in elite]))

[(array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 0, 0, 0, 1, 1, 1]), 80),
 (array([1, 1, 0, 0, 1, 1, 0]), 73),
 (array([1, 1, 0, 0, 1, 1, 0]), 73),
 (array([1, 1, 0, 0, 1, 1, 0]), 73),
 (array([1, 1, 0, 0, 1, 1, 0]), 73),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 1, 1, 0, 1, 0, 1]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 1, 1, 1, 0]), 72),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 (array([1, 0, 0, 0, 1, 1, 0]), 70),
 

In [75]:
parent = get_child()
counter = 0
while counter < 1000:
    nbits = np.random.choice([1, 2, 3], p=[0.5, 0.2, 0.3])
    child = mutate(parent, nbits=nbits)
    if fitness(child) > fitness(parent):
        print('Swap')
        parent = child.copy()
    counter += 1
    if counter % 100 == 0:
        print(parent, fitness(parent))

Swap
Swap
Swap
Swap
[1 1 0 0 1 1 0] 73
[1 1 0 0 1 1 0] 73
[1 1 0 0 1 1 0] 73
Swap
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
[1 0 0 0 1 1 1] 80
