In [2]:
import os

In [27]:
!pip install "matplotlib==1.0.1"


  Using cached https://files.pythonhosted.org/packages/b9/16/46f8f512884a2f13ee29ff3bb25d0d6996ac90bf5d38f07ede39e2fe6ddf/matplotlib-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PRASHA~1\AppData\Local\Temp\pip-install-txc49vyg\matplotlib\setup.py", line 238
        print 'adding pytz'
                          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('adding pytz')?
    
    ----------------------------------------


Command "python setup.py egg_info" failed with error code 1 in C:\Users\PRASHA~1\AppData\Local\Temp\pip-install-txc49vyg\matplotlib\


In [26]:
!pip install --upgrade setuptools


  Found existing installation: setuptools 40.2.0
    Uninstalling setuptools-40.2.0:
      Successfully uninstalled setuptools-40.2.0


twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.


In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


ImportError: cannot import name '_path' from 'matplotlib' (C:\Users\Prashanth Yerabati\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py)

In [3]:
train = pd.read_csv('train_sample.csv')
test = pd.read_csv('test_sample.csv')
x_train = train.iloc[:,1:]
y_train = train.iloc[:,0]
x_test = test.iloc[:,1:]
y_test = test.iloc[:,0]

x1 = train.iloc[0,:].values.reshape(28,28)

In [4]:
print(x_train.shape)
print(y_train.shape)
x1 = x_train.iloc[0,:].values.reshape(28,28)
x1[x1 > 0 ] = 1

(5000, 784)
(5000,)


In [5]:
print(x_test.shape)
print(y_test.shape)

(1000, 784)
(1000,)


In [6]:
train_sample = np.random.choice(range(0,x_train.shape[0]),replace = False, size =5)
test_sample = np.random.choice(range(0,x_test.shape[0]),replace=False, size=5)

In [7]:
train_sample

array([3327, 2639, 3333, 1924, 1145])

In [8]:
test_sample

array([200, 628, 632,   9, 422])

In [ ]:
plt.figure(figsize=(10,5))
for i,j in enumerate(train_sample):
    plt.subplot(1,5, i+1) # 1 row and 5 columns
    plt.imshow(x_train.iloc[j,:].values.reshape(28,28))
    plt.title("Digit:" + str(y_train[j]))
    plt.gray()
    

In [15]:
!pip install matplotlib==1.0.1

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\PRASHA~1\AppData\Local\Temp\pip-install-p454ufpg\matplotlib\setup.py", line 238
        print 'adding pytz'
                          ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print('adding pytz')?
    
    ----------------------------------------


Command "python setup.py egg_info" failed with error code 1 in C:\Users\PRASHA~1\AppData\Local\Temp\pip-install-p454ufpg\matplotlib\


In [ ]:
plt.figure(figsize=(10,5))
for i, j in enumerate(test_sample):
    plt.subplot(1,5, i+1)
    plt.imshow(x_test.iloc[j,:].values.reshape(28,28))
    plot.title("Digit:" + str(y_test[j]))
    plt.gray()

In [9]:
knn_classifier = KNeighborsClassifier(n_neighbors=3,weights="distance",algorithm="brute")

In [11]:
knn_classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='distance')

In [12]:
pred_test = knn_classifier.predict(x_test)

In [13]:
pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 7, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3,

cm_test = confusion_matrix(y_pred=pred_test, y_true=y_test)
print(cm_test)
sum(np.diag(cm_test))/np.sum(cm_test)

In [20]:
misclassfied = y_test[pred_test != y_test]

In [22]:
# First Five Missclassified rows
misclassfied.index[:5]

Int64Index([83, 97, 224, 246, 286], dtype='int64')

In [ ]:
plt.figure(figsize=(10,5))
for i, j in enumerate(misclassified.index[:5]):
    plt.subplot(1,5,i+1)
    plt.imshow(x_test.iloc[j,:].values.reshape(28,28))
    plt.title("Digits:"+str(y_test[j])+" "+"Pred:"+str(pred_test[j]))
    plt.gray()
