In [1]:
import os

In [2]:
os.getcwd()

'C:\\Users\\Prashanth Yerabati\\Python Lab'

In [3]:
pi=3.14

In [4]:
api = 3.1

In [5]:
pi+api

6.24

In [6]:
t = True
print(t,type(t))
t,f = True, False
print(t,f)

True <class 'bool'>
True False


In [7]:
a = 'hello'
a.capitalize()
a.title()
a.upper()
a = '   hello'
x=a.strip()
x
x=a.lstrip()
x
a = 'hello  '
x=a.rstrip()
x ='Prashanth, Yerabati'
x.split(",")
x



'Prashanth, Yerabati'

In [8]:
x = 'Prashanth/Yerabati'
x = x.split('/')
x = x[1]
print(x)

Yerabati


In [9]:
x = 'pavan kumar'
x.join('AB')
x.join('ABC')

'Apavan kumarBpavan kumarC'

In [10]:
x ='pavan'
x.index('a')

1

In [11]:
y=enumerate(x)
list(y)
type(y)
y

In [12]:
k = 'Hello I am Prashanth'
k = k.split()
print(k)
print(len(k))

['Hello', 'I', 'am', 'Prashanth']
4


In [17]:
print(t or f)
print(t and f)
print(t|f)
print(not t)
3!=4


True
False
True
False


True

In [21]:
a = [1,3,4,6,23,26]
a[-1]
a[-3:]

[6, 23, 26]

In [27]:
a = [1,2,3]
b = [4,5,6]
a.append(4)
a
x = [11,24,36]
a.append(x)
a
a.extend(x)
a


[1, 2, 3, 4, [11, 24, 36], 11, 24, 36]

In [37]:
a = [1,2,1,1,3,1,1,6,7,8]
a.count(1)
a.pop()
a
a.remove(6)
a
a.insert(2,100)
a
a[2] =1000
a

[1, 2, 1000, 1, 1, 3, 1, 1, 7]

In [40]:
mylist = ['a', [1,2,3], 'abc']
mylist.append('batch')
mylist
mylist.remove('abc')
mylist

['a', [1, 2, 3], 'batch']

In [5]:
a = [1,2,3,4]
b = [5,6,7,8]
c = a + b
c
c
c.append('alpha')
c
c.insert(2,'alpha')
c
x = [1,4,5]
c.append(x)
c
c.extend(x)
c
range(5)
list(range(5))
x = list(range(1,10,2))
x
x[0]
x[1] = 100
x



[1, 100, 5, 7, 9]

In [55]:
x = 'pavan'
x[0]

'p'

In [61]:
x = 200
res=2 if x>200 else 3 if x>300 else 4
print(res)

4


In [4]:
a = [10,-13,15,26]
a[1:3]


[-13, 15]

In [76]:
a = list(range(1,51))
print(a)
b = []
c = []
for i in a:
    if (i%2==0):
        b.append(i)
print(b)
for i in range(len(a)):
    if ((a[i])%2==0):
         c.insert(i,a[i])
print(c)       

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


In [77]:
def add(a,b):
    return a+b
add(3,5)


8

In [81]:
a = range(1,50)
b = [i**2 for i in a if i%2==0 ]
print(b)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304]


In [82]:
a = range(1,50)
b = []
for i in a:
    if i%2==0:
        b.append(1)
    else:
        b.append(0)
print(b)
    

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]


In [25]:
a = [1,3,5,7,9]
b = set(a)
b
for i in b:
    print(i)


{1, 3, 5, 7, 9}

In [86]:
a=(1,2,3)
a[0]
a[1:3]

(2, 3)

In [92]:
dict1 = {'a':1, 'b':2, 'c':3}
for k in dict1:
    print(k,dict1[k])
value = 2
for k in dict1:
    if (value==dict1[k]):
        print(k)
    

a 1
b 2
c 3
b


In [27]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,type(a))
np.subtract(a,b)
np.add(a,b)
np.multiply(a,b)
np.divide(a,b)

[1 2 3] <class 'numpy.ndarray'>


array([-3, -3, -3])

In [102]:
a=np.array([[1,2,3],[4,5,6]])
a.shape


(2, 3)

In [28]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape
a[1:,]

array([[3, 4],
       [5, 6]])

In [29]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
a.shape
a


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [30]:
a[:,:,1:3]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

In [31]:
a[1,1:,3:4]

array([[ 8],
       [12]])