In [1]:
import os


In [2]:
os.getcwd()


'C:\\Users\\Prashanth Yerabati\\Python Lab'

In [4]:
pi = 3.14

In [9]:
# Variables
api = 3.14
print(pi+api)
print(pi-api)
print(pi*api)
print(pi/api)
print(pi**2)

6.28
0.0
9.8596
1.0
9.8596


In [1]:
# Bolean type of variables
t=True
print(t,type(t))
t,f = True,False
print(t,f)



True <class 'bool'>
True False


In [25]:

## Strings
a='Hello'
b ="Hello"
c='x'
print(a,b)
print(type(a))
print(type(c))
type(a)

Hello Hello
<class 'str'>
<class 'str'>


str

In [65]:
## Methods to Manipulate the Variables
a='hello'
a.capitalize()
a.title()
a.upper()
a = a.upper()
a = '   hello'
print(a)
x=a.strip()
x
x.startswith('h')
x ='prashanth'
x.startswith('a',2)
x = 'satish   '
x.rstrip()
x.islower()
x = 'Prashanth,Yerabati'
x.split(",")
y = 'Prashanth/Ravi/Satish/test'
y.split("/", maxsplit=3)
x = 'pavan'
x.count('a')
x='Prashanth Yerabati'x=x.split()
x=(x,1)
print(x)
x = 'pavan kumar'
x.join('AB')
x.join('ABC')

   hello
(['Prashanth', 'Yerabati'], 1)


'Apavan kumarBpavan kumarC'

In [67]:
x = 'pavan'
x.index('a')

1

In [70]:
#enumeric
y = enumerate(x)
list(y)
type(y)

enumerate

In [81]:

## Concatenation
irststring = 'I am'
secondstring ='INSOFE Batch'
batchNo = 53
print("Hello there:"+firststring.upper()+' ' +"FROM "+secondstring.upper()+str(batchNo)+"!!!")

Hello there:I AM FROM INSOFE BATCH53!!!


In [1]:
## Separation or Split
k = 'Hello I am Prashanth'
k = k.split()
print(k)
print(len(k))

['Hello', 'I', 'am', 'Prashanth']
4


In [92]:
# Split
k = k.split()
print(k)

['Hello', 'I', 'am', 'Prashanth']


In [97]:
# logical operator
t and f
print(t or f)
print(t and f)
print(t|f)
print(not t)
3!=4


True
False
True
False


True

In [102]:

# Relational operator
print(not t |3<4)
x=3
print(x!=3 | x<4)
print(x==3 & x<4)

False
False
True


In [103]:

# List
a = [1, 2,3,4, 5]
a[0]
a[-1]
a[-3]

3

In [122]:
a = [1,3,4,6,23]
print(a[1:4])
print(a[:3])
print(a[3:])
print(a[-1:])
print(a[-3:])
print(a[-1:])
print(a[:-1])
print(a[-1:-3])


[3, 4, 6]
[1, 3, 4]
[6, 23]
[23]
[4, 6, 23]
[23]
[1, 3, 4, 6]
[]


In [123]:
a = [1,2,3]
b =[4,5,6]
a.append(4)
x = [11, 24, 36]
a.append(x)
a
a.extend(x)
a

[1, 2, 3, 4, [11, 24, 36], 11, 24, 36]

In [130]:
a = [1,2,3,4,1,1,1,7]
a.count(1)
a.pop()
a
a.remove(4)
a.insert(2,100)
a
a[2] = 1000
a

[1, 2, 1000, 3, 1, 1, 1]

In [133]:
mylist = ['a', [1,2,3], 'abc']
mylist.append('batch')
mylist.remove([1,2,3])
mylist

['a', 'abc', 'batch']

In [139]:
msl=['a','b',23,True]
msl[-1]
msl[1] = 'bat'
msl

['a', 'bat', 23, True]

In [150]:
a = [1,2,3,4]
b = [5,6,7,8]
c = a + b
c
c.append('alpha')
c
c.insert(2,'alpha')
x = [1,4,5]
c.append(x)
c.extend(x)
c
range(5)
list(range(5))
list(range(1,10))
x=list(range(1,10,2))
x[0]
x[0] = 100
x




[100, 3, 5, 7, 9]

In [151]:
x = 'pavan'
x[0]

'p'

In [ ]:
x=int(input("Please enter a number"))

In [ ]:
if x>0:
    
    ('entered number is positive')
else:
    print(enterd number is negative')

In [2]:
x = int(input("please enter the trasaction amount"))

please enter the trasaction amount 3000


In [ ]:
if x > 1000:
    print("Transaction amount is too low")
elif x  > 2000:
    print("Transaction amount is low")
else:
    print("transaction amount is high")

In [1]:
x=int(input("Please enter the value of x"))
amt = 2 if x<1000 else 1 if x<2000 else 0
print(amt)

Please enter the value of x 1500


1


In [ ]:
a=[10,23,15,16]
for i in range(len(a)):
    if a[i] > 0 :
        print("The number is positive",a[i])
    else:
        print("the number is negative",a[i])
    


In [7]:
i=0
while(i<=10):
    i=i+2
    print("The even numbers less than 10 are ",i)
    

The even numbers less than 10 are  2
The even numbers less than 10 are  4
The even numbers less than 10 are  6
The even numbers less than 10 are  8
The even numbers less than 10 are  10
The even numbers less than 10 are  12


In [10]:
a=list(range(1,50))
b=[]
for i in a :
    if i%2==0:
        b.append(i)
b

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48]

In [17]:
a = list(range(1,50))
b = []
for i in range(len(a)):
    if a[i]%2==0:
        b.insert(i,a[i])
print(b)
        

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [20]:
def add(a,b):
    return a+b

add(4,5)
    

9


In [21]:
add(10,11)

21


In [18]:
a = range(1,50)
b = [i for i in a if i%2==0]
b = [i**2 for i in a if i%2==0]


In [ ]:
a = range(1,50) 
b = []
for i in a:
    if i%2==0;
        b.append(1)
    else:
        b.append(0)
print(a,)
print(b,)
b = [1 for i in a if i%2==0  ]


In [3]:
a = [1,2,3,5,7]
b = set(a)
b
for i in b:
    print(i)


1
2
3
5
7


In [4]:
a = (1,2,3)
type(a)
a[0]
a[1:3]


tuple

In [6]:
x = [('a',1),('b',2),('c',3)]
x[0][1]
x[1][0]

'b'

In [6]:
dict1={'a': 1, 'b':2, 'c':3}
dict1.keys()
dict1.values()
for key in dict1:
    print(key,dict1[key])
value=2
for k,v in dict1.items():
    if (value==dict1[k]):
        print(k)
    



a 1
b 2
c 3
b


In [12]:
dict1['d']=4

In [22]:
def method(dict1,value):
    for k, v in dict1.iteritems():
        if v == value:
            yield k
    for r in method(dict1,2):
        print(r)

In [21]:
a = [2,3,4]
b = [6,7,8]
c=[]
for i in range(len(a)):
    c.append(a[i]+b[i])

c

[8, 10, 12]

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a,type(a))
np.subtract(a,b)
np.divide(a,b)
np.multiply(a,b)

[1 2 3] <class 'numpy.ndarray'>


array([ 4, 10, 18])

In [4]:
a=np.array([[1,2],[3,4]])
a.shape

(2, 2)

In [19]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [20]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape
a[1,1]
a[1,:]

array([3, 4])

In [4]:
three_dim_array=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
three_dim_array
three_dim_array.shape


(3, 3, 4)