In [45]:
import os
import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import dendrogram,linkage
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.cluster  import KMeans

In [12]:
x = np.array([[1,2],[1,3],[3,2],[2,4],[4,3],[15,16],[16,16],[15,15],[15,20],[20,17]])

In [ ]:
plt.scatter(x[:,0],x[:,1], c = cluster_2.labels_, cmap='rainbow')

In [21]:
## Affiniity will tell you the distance type, it can be ecludean or manhatten
## Linkeage <- Single likeage considers the distance between the nearest point in the cluster and the point and assigns to that cluster
## Complete <- complete likeage considers the distance between the farthest point in the cluster and the point and assigns to that cluster
## Average <- complete likeage considers the distances between the point in the cluster and the point and assigns average distance   to that cluster

cluster_2 = AgglomerativeClustering(n_clusters=2, affinity='euclidean', linkage='average')
cluster_2.fit_predict(x)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
cluster_3 = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='average')
cluster_3.fit_predict(x)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 2], dtype=int64)

In [28]:
clust = linkage(x, metric='euclidean',method="average")
clust1 = dendrogram(clust)

ImportError: You must install the matplotlib library to plot the dendrogram. Use no_plot=True to calculate the dendrogram without plotting.

In [30]:
mtcars = pd.read_csv("mtcars.csv")

In [41]:
numeric_vars = mtcars.drop(['cyl','vs','am','gear','carb'],axis=1)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
mpg     32 non-null float64
disp    32 non-null float64
hp      32 non-null int64
drat    32 non-null float64
wt      32 non-null float64
qsec    32 non-null float64
dtypes: float64(5), int64(1)
memory usage: 1.6 KB


KeyError: ('mpg', 'disp', 'drat', 'wt', 'qsec')

In [42]:
numeric_vars
std= StandardScaler()
std.fit(numeric_vars)
numeric_train_std = std.transform(numeric_vars)

In [43]:
numeric_vars

mpg   disp   hp  drat     wt   qsec
0   21.0  160.0  110  3.90  2.620  16.46
1   21.0  160.0  110  3.90  2.875  17.02
2   22.8  108.0   93  3.85  2.320  18.61
3   21.4  258.0  110  3.08  3.215  19.44
4   18.7  360.0  175  3.15  3.440  17.02
5   18.1  225.0  105  2.76  3.460  20.22
6   14.3  360.0  245  3.21  3.570  15.84
7   24.4  146.7   62  3.69  3.190  20.00
8   22.8  140.8   95  3.92  3.150  22.90
9   19.2  167.6  123  3.92  3.440  18.30
10  17.8  167.6  123  3.92  3.440  18.90
11  16.4  275.8  180  3.07  4.070  17.40
12  17.3  275.8  180  3.07  3.730  17.60
13  15.2  275.8  180  3.07  3.780  18.00
14  10.4  472.0  205  2.93  5.250  17.98
15  10.4  460.0  215  3.00  5.424  17.82
16  14.7  440.0  230  3.23  5.345  17.42
17  32.4   78.7   66  4.08  2.200  19.47
18  30.4   75.7   52  4.93  1.615  18.52
19  33.9   71.1   65  4.22  1.835  19.90
20  21.5  120.1   97  3.70  2.465  20.01
21  15.5  318.0  150  2.76  3.520  16.87
22  15.2  304.0  150  3.15  3.435  17.30
23  13.3  350.0  245  3.73  3.840  15.41
24  19.2  400.0  175  3.08  3.845  17.05
25  27.3   79.0   66  4.08  1.935  18.90
26  26.0  120.3   91  4.43  2.140  16.70
27  30.4   95.1  113  3.77  1.513  16.90
28  15.8  351.0  264  4.22  3.170  14.50
29  19.7  145.0  175  3.62  2.770  15.50
30  15.0  301.0  335  3.54  3.570  14.60
31  21.4  121.0  109  4.11  2.780  18.60

In [47]:
wss = {}
for k in range(1, 15):
    kmeans = KMeans(n_clusters=k, max_iter=1000).fit(numeric_train_std )
    #clusters = kmeans.labels_
    wss[k] = kmeans.inertia_ ## Inertia: Sum of squared distances of sample to the 

In [48]:
wss

{1: 192.0,
 2: 90.11043015327019,
 3: 68.22602361405987,
 4: 54.15567987741812,
 5: 39.452946762401005,
 6: 30.85267577202092,
 7: 25.454151239330017,
 8: 22.167374689070044,
 9: 18.623741938949657,
 10: 15.792142424316339,
 11: 13.934848571426597,
 12: 12.727557412325105,
 13: 10.37344646501589,
 14: 8.778426983646405}

In [49]:
cluster_4 = AgglomerativeClustering(n_clusters=8, affinity='euclidean', linkage='average')
cluster_4.fit_predict(numeric_train_std)

array([0, 0, 0, 6, 7, 6, 1, 0, 5, 0, 0, 7, 7, 7, 4, 4, 4, 2, 2, 2, 0, 7,
       7, 1, 7, 2, 3, 3, 1, 0, 1, 0], dtype=int64)

In [50]:
clust5 = linkage(numeric_train_std, metric='euclidean',method="average")
clust6 = dendrogram(clust)

ImportError: You must install the matplotlib library to plot the dendrogram. Use no_plot=True to calculate the dendrogram without plotting.